//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using DAL.Interfaces;

namespace DAL
{
    using System;
    using System.Collections.Generic;

    public partial class Question : IEntity
    {
        public Question()
        {
            this.Variants = new HashSet<Variant>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public int TestId { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual ICollection<Variant> Variants { get; set; }
    }
}
